from backend.app.models.athletes import Athletes
from backend.app.models.athlete_participations import AthleteParticipations
from backend.app.models.games import Games
from backend.app.models.coaches import Coaches
from backend.app.models.medals import Medals
from backend.app.models.events import Events
from backend.app.models.countries import Countries
from backend.app.models.sports import Sports
from backend.app.models.eventssports import EventsSports